services:
  web:
    build: ../rpg-online
    container_name: rpg-online
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - rpg-api-network

  app:
    build: .
    container_name: rpg-api
    ports:
      - "8080:80"
    volumes:
      - ./writable:/var/www/html/writable
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rpg-api-network

  db:
    image: mysql:8.0
    container_name: rpg-api-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - rpg-api-network

volumes:
  db_data:

networks:
  rpg-api-network:
    driver: bridge
